[project]
name = "SpheroidPy"
version = "0.1.0"
description = "Python Package for the Spatial and Temporal Analysis of Spheroid Imaging Data"
authors = [
    { name = "Cedric Heuermann", email = "cedric.heuermann@tumoroid.org" }
]
readme = "readme.md"
requires-python = ">=3.10,<3.12"

license = { text = "GPL-3.0-or-later" }

dependencies = [
    "h5py>=3.11,<4",
    "ipython>=8.12,<9",
    "ipywidgets>=8.1,<9",
    "PyQt5>=5.15,<6",
    "matplotlib>=3.8,<4",
    "numpy>=1.26,<2",
    "opencv-python>=4.9,<5",
    "openpyxl>=3.1,<4",
    "pandas>=2.3,<3",
    "Pillow>=10,<11",
    "psutil>=5.9,<6",
    "scipy>=1.9,<2",
    "seaborn>=0.13,<0.14",
    "Shapely>=2,<3",
    "scikit-image>=0.23,<0.24",
    "tifffile>=2024.2,<2025",
    "tqdm>=4.66,<5",
    "tables>=3.8,<4",
    "olefile>=0.47,<1",
    "torch==2.2.2", 
    "torchvision==0.17.2"
]

[project.optional-dependencies]
pde = ["MeshPy"]
all = ["MeshPy"]

[project.urls]
homepage = "https://tumoroid.org"
repository = "https://github.com/tumoroids/SpheroidPy"
issues = "https://github.com/tumoroids/SpheroidPy/issues"
documentation = "https://tumoroid.org"


[build-system]
requires = ["setuptools==68.2.2", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = ["SpheroidPy", "SpheroidPy.spheroid",
            "SpheroidPy.experiment", "SpheroidPy.utils"]

[tool.setuptools.package-data]
SpheroidPy = ["static/images/*.png"]
