[project]
name = "SpheroidPy"
version = "0.1.0"
description = "Python Package for the Spatial and Temporal Analysis of Spheroid Imaging Data"
authors = [
    { name = "Cedric Heuermann", email = "cedric.heuermann@tumoroid.org" }
]
readme = "readme.md"
requires-python = ">=3.10"

license = { text = "GPL-3.0-or-later" }

dependencies = [
    "h5py",
    "ipython",
    "ipywidgets",
    "ipympl",
    "PyQt5",
    "matplotlib",
    "numpy",
    "opencv-python",
    "openpyxl",
    "pandas",
    "Pillow",
    "psutil",
    "scipy",
    "seaborn",
    "Shapely",
    "scikit-image",
    "tifffile",
    "tqdm",
    "tables",
    "olefile",
    "setuptools==68.2.2",
    "torch==2.2.2", 
    "torchvision==0.17.2"
]

[project.optional-dependencies]
pde = ["MeshPy"]
all = ["MeshPy"]

[project.urls]
homepage = "https://tumoroid.org"
repository = "https://github.com/tumoroids/SpheroidPy"
issues = "https://github.com/tumoroids/SpheroidPy/issues"
documentation = "https://tumoroid.org"  # optional


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = ["SpheroidPy", "SpheroidPy.spheroid",
            "SpheroidPy.experiment", "SpheroidPy.utils"]

[tool.setuptools.package-data]
SpheroidPy = ["static/images/*.png"]
